//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTools.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTools.Graphics.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0048BA|Absolute Zero
        ///B0BF1A|Acid green
        ///7CB9E8|Aero
        ///C0E8D5|Aero blue
        ///B284BE|African violet
        ///72A0C1|Air superiority blue
        ///EDEAE0|Alabaster
        ///F0F8FF|Alice blue
        ///C46210|Alloy orange
        ///EFDECD|Almond
        ///E52B50|Amaranth
        ///9F2B68|Amaranth (M&amp;P)
        ///F19CBB|Amaranth pink
        ///AB274F|Amaranth purple
        ///D3212D|Amaranth red
        ///3B7A57|Amazon
        ///FFBF00|Amber
        ///FF7E00|Amber (SAE/ECE)
        ///9966CC|Amethyst
        ///A4C639|Android green
        ///CD9575|Antique brass
        ///665D1E|Antique bronze
        ///915C83|Antique fuchsia
        ///841B2D|Antique ruby
        ///FAEBD7|Antique white
        ///0080 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColorList {
            get {
                return ResourceManager.GetString("ColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFFFFF|White
        ///C0C0C0|Silver
        ///808080|Gray
        ///000000|Black
        ///FF0000|Red
        ///800000|Maroon
        ///FFFF00|Yellow
        ///808000|Olive
        ///00FF00|Lime
        ///008000|Green
        ///00FFFF|Aqua
        ///008080|Teal
        ///0000FF|Blue
        ///000080|Navy
        ///FF00FF|Fuchsia
        ///800080|Purple
        ///C71585|MediumVioletRed
        ///FF1493|DeepPink
        ///DB7093|PaleVioletRed
        ///FF69B4|HotPink
        ///FFB6C1|LightPink
        ///FFC0CB|Pink
        ///8B0000|DarkRed
        ///FF0000|Red
        ///B22222|Firebrick
        ///DC143C|Crimson
        ///CD5C5C|IndianRed
        ///F08080|LightCoral
        ///FA8072|Salmon
        ///E9967A|DarkSalmon
        ///FFA07A|LightSalmon
        ///FF4500|OrangeRed
        ///FF6347|Tomato
        ///FF8C00|DarkOrange
        ///FF7F50|Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebPalette {
            get {
                return ResourceManager.GetString("WebPalette", resourceCulture);
            }
        }
    }
}
