// ************************************************* ''
// DataTools C# Native Utility Library For Windows - Interop
//
// Module: UsbHid
//         HID-related structures, enums and functions.
//
// Copyright (C) 2011-2020 Nathan Moschkin
// All Rights Reserved
//
// Licensed Under the MIT License   
// ************************************************* ''

using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace DataTools.Win32
{
    public enum HidPowerUsageCode : byte
    {
        Undefined = 0x0,
        Name = 0x1,
        PresentStatus = 0x2,
        ChangedStatus = 0x3,
        UPS = 0x4,
        PowerSupply = 0x5,
        Reserved1 = 0x6,
        Reserved2 = 0x7,
        Reserved3 = 0x8,
        Reserved4 = 0x9,
        Reserved5 = 0xA,
        Reserved6 = 0xB,
        Reserved7 = 0xC,
        Reserved8 = 0xD,
        Reserved9 = 0xE,
        Reserved10 = 0xF,
        BatterySystem = 0x10,
        BatterySystemID = 0x11,
        Battery = 0x12,
        BatteryID = 0x13,
        Charger = 0x14,
        ChargerID = 0x15,
        PowerConverter = 0x16,
        PowerConverterID = 0x17,
        OutletSystem = 0x18,
        OutletSystemID = 0x19,
        Input = 0x1A,
        InputID = 0x1B,
        Output = 0x1C,
        OutputID = 0x1D,
        Flow = 0x1E,
        FlowID = 0x1F,
        Outlet = 0x20,
        OutletID = 0x21,
        Gang = 0x22,
        GangID = 0x23,
        PowerSummary = 0x24,
        PowerSummaryID = 0x25,
        Reserved25 = 0x2F,
        Voltage = 0x30,
        Current = 0x31,
        Frequency = 0x32,
        ApparentPower = 0x33,
        ActivePower = 0x34,
        PercentLoad = 0x35,
        Temperature = 0x36,
        Humidity = 0x37,
        BadCount = 0x38,
        Reserved39 = 0x3F,
        ConfigVoltage = 0x40,
        ConfigCurrent = 0x41,
        ConfigFrequency = 0x42,
        ConfigApparentPower = 0x43,
        ConfigActivePower = 0x44,
        ConfigPercentLoad = 0x45,
        ConfigTemperature = 0x46,
        ConfigHumidity = 0x47,
        Reserved38 = 0x4F,
        SwitchOnControl = 0x50,
        SwitchOffControl = 0x51,
        ToggleControl = 0x52,
        LowVoltageTransfer = 0x53,
        HighVoltageTransfer = 0x54,
        DelayBeforeReboot = 0x55,
        DelayBeforeStartup = 0x56,
        DelayBeforeShutdown = 0x57,
        Test = 0x58,
        ModuleReset = 0x59,
        AudibleAlarmControl = 0x5A,
        Reserved11 = 0x5B,
        Reserved12 = 0x5C,
        Reserved13 = 0x5D,
        Reserved14 = 0x5E,
        Reserved15 = 0x5F,
        Present = 0x60,
        Good = 0x61,
        InternalFailure = 0x62,
        VoltageOutOfRange = 0x63,
        FrequencyOutOfRange = 0x64,
        Overload = 0x65,
        OverCharged = 0x66,
        OverTemperature = 0x67,
        ShutdownRequested = 0x68,
        ShutdownImminent = 0x69,
        Reserved16 = 0x6A,
        SwitchOn = 0x6B,
        SwitchOff = 0x6B,
        Switchable = 0x6C,
        Used = 0x6D,
        Boost = 0x6E,
        Buck = 0x6F,
        Initialized = 0x70,
        Tested = 0x71,
        AwaitingPower = 0x72,
        CommunicationLost = 0x73,
        Reserved7Min = 0x74,
        Reserved7Max = 0xFC,
        Manufacturer = 0xFD,
        Product = 0xFE,
        SerialNumber = 0xFF
    }
}
