//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreTestOne.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreTestOne.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Skies.
        /// </summary>
        internal static string ExampleEnum_Blue {
            get {
                return ResourceManager.GetString("ExampleEnum_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden Rays.
        /// </summary>
        internal static string ExampleEnum_Gold {
            get {
                return ResourceManager.GetString("ExampleEnum_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdant Groves.
        /// </summary>
        internal static string ExampleEnum_Green {
            get {
                return ResourceManager.GetString("ExampleEnum_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet Sunset.
        /// </summary>
        internal static string ExampleEnum_Purple {
            get {
                return ResourceManager.GetString("ExampleEnum_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson Fowl.
        /// </summary>
        internal static string ExampleEnum_Red {
            get {
                return ResourceManager.GetString("ExampleEnum_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Sheen.
        /// </summary>
        internal static string ExampleEnum_Silver {
            get {
                return ResourceManager.GetString("ExampleEnum_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prop Tens.
        /// </summary>
        internal static string Proptens {
            get {
                return ResourceManager.GetString("Proptens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classy 20&apos;s Style.
        /// </summary>
        internal static string SampleBaseClass {
            get {
                return ResourceManager.GetString("SampleBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is mythological.
        /// </summary>
        internal static string SampleBaseClass_ValueA {
            get {
                return ResourceManager.GetString("SampleBaseClass_ValueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Integral.
        /// </summary>
        internal static string SampleBaseClass_ValueI {
            get {
                return ResourceManager.GetString("SampleBaseClass_ValueI", resourceCulture);
            }
        }
    }
}
