//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTools.Win32.Usb.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTools.Win32.Usb.Globalization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _01 {
            get {
                object obj = ResourceManager.GetObject("_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _02 {
            get {
                object obj = ResourceManager.GetObject("_02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _03 {
            get {
                object obj = ResourceManager.GetObject("_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _04 {
            get {
                object obj = ResourceManager.GetObject("_04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _05 {
            get {
                object obj = ResourceManager.GetObject("_05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _06 {
            get {
                object obj = ResourceManager.GetObject("_06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _07 {
            get {
                object obj = ResourceManager.GetObject("_07", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _08 {
            get {
                object obj = ResourceManager.GetObject("_08", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _09 {
            get {
                object obj = ResourceManager.GetObject("_09", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _59 {
            get {
                object obj = ResourceManager.GetObject("_59", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _80 {
            get {
                object obj = ResourceManager.GetObject("_80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _81 {
            get {
                object obj = ResourceManager.GetObject("_81", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _82 {
            get {
                object obj = ResourceManager.GetObject("_82", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _84 {
            get {
                object obj = ResourceManager.GetObject("_84", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _85 {
            get {
                object obj = ResourceManager.GetObject("_85", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _90 {
            get {
                object obj = ResourceManager.GetObject("_90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _91 {
            get {
                object obj = ResourceManager.GetObject("_91", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Collection.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Application) Applies a name to a top level collection which the operating system uses to identify a device and possibly remap to a legacy API..
        /// </summary>
        internal static string CA_GUIDE {
            get {
                return ResourceManager.GetString("CA_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Collection.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Logical) A logical collection of items..
        /// </summary>
        internal static string CL_GUIDE {
            get {
                return ResourceManager.GetString("CL_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Collection.
        /// </summary>
        internal static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Physical) A physical collection of items..
        /// </summary>
        internal static string CP_GUIDE {
            get {
                return ResourceManager.GetString("CP_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Flag.
        /// </summary>
        internal static string DF {
            get {
                return ResourceManager.GetString("DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Data, Variable, Absolute) A read/write single-bit value..
        /// </summary>
        internal static string DF_GUIDE {
            get {
                return ResourceManager.GetString("DF_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Value.
        /// </summary>
        internal static string DV {
            get {
                return ResourceManager.GetString("DV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Data, Variable, Absolute) A read/write multiple-bit value..
        /// </summary>
        internal static string DV_GUIDE {
            get {
                return ResourceManager.GetString("DV_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Control.
        /// </summary>
        internal static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Ion.
        /// </summary>
        internal static string LION {
            get {
                return ResourceManager.GetString("LION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentary Control.
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Array.
        /// </summary>
        internal static string NAry {
            get {
                return ResourceManager.GetString("NAry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Logical) A collection that encompasses an array definition, naming the array set or the field created by the array..
        /// </summary>
        internal static string NAry_GUIDE {
            get {
                return ResourceManager.GetString("NAry_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Cadmium.
        /// </summary>
        internal static string NiCd {
            get {
                return ResourceManager.GetString("NiCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Metal Hydride.
        /// </summary>
        internal static string NiMH {
            get {
                return ResourceManager.GetString("NiMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel Zinc.
        /// </summary>
        internal static string NiZn {
            get {
                return ResourceManager.GetString("NiZn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off Control.
        /// </summary>
        internal static string OOC {
            get {
                return ResourceManager.GetString("OOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Shot Control.
        /// </summary>
        internal static string OSC {
            get {
                return ResourceManager.GetString("OSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Acid.
        /// </summary>
        internal static string pbAc {
            get {
                return ResourceManager.GetString("pbAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechargeable Alkaline.
        /// </summary>
        internal static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-trigger Control.
        /// </summary>
        internal static string RTC {
            get {
                return ResourceManager.GetString("RTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector Array Contained in a Named Array.
        /// </summary>
        internal static string Sel {
            get {
                return ResourceManager.GetString("Sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Flag.
        /// </summary>
        internal static string SF {
            get {
                return ResourceManager.GetString("SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Constant, Variable, Absolute) A read-only single-bit value..
        /// </summary>
        internal static string SF_GUIDE {
            get {
                return ResourceManager.GetString("SF_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Value.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Constant, Variable, Absolute) A read-only multiple-bit value..
        /// </summary>
        internal static string SV_GUIDE {
            get {
                return ResourceManager.GetString("SV_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Modifier.
        /// </summary>
        internal static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Logical) Modifies the purpose or function of the Usages (controls) that contains it..
        /// </summary>
        internal static string UM_GUIDE {
            get {
                return ResourceManager.GetString("UM_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Switch.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Logical) Modifies the purpose or function of the Usages (controls) that it contains..
        /// </summary>
        internal static string US_GUIDE {
            get {
                return ResourceManager.GetString("US_GUIDE", resourceCulture);
            }
        }
    }
}
